### ISSUE TITLE
HTTP 500 error when trying to Issue an ERC-20 on Mainnet

### ISSUE THREAD

**Issue by cyan-one** [fuseio/fuse-studio#339]
<img width="1300" alt="Bildschirmfoto 2020-06-26 um 15 41 30" src="https://user-images.githubusercontent.com/43147663/85863774-ec594300-b7c3-11ea-93e5-80bfd58c1943.png">

**Comment by leonprou** [comment]
Thanks for reporting 🙂
It seems that one of our backend services was down, so the metadata of the community wasn't store. Can you try again?

**Comment by cyan-one** [comment]
Sure, thanks for the response. I just tried it again and still get an error:
<img width="900" alt="Bildschirmfoto 2020-06-30 um 10 53 20" src="https://user-images.githubusercontent.com/43147663/86105821-1b233200-bac0-11ea-952c-93efd9ed8bb1.png">

**Comment by leonprou** [comment]
@cyan-one I see, couldn't replicate it myself..
This happens before you sign the transaction with Metamask, right?

**Comment by cyan-one** [comment]
yes it stops before metamask pops up

**Comment by leonprou** [comment]
@cyan-one You can mail me on leon@fuse.io with your contact data (like a telegram handle) and we can do this live
