### ISSUE TITLE
Transfer ERC20 Token back to origin wallet

### ISSUE THREAD

**Issue by fluse** [fuseio/fuse-studio#481]
Hello together:

Issue Facts
Community: 0xfd3b235313A0423d7fc4A99676E6d1FD70bd9c6B
Origin Network: ETH MainNetwork

I transfered 99000 ERC20 BTM from MainNet to fuse network,
How can i transfer this sum of my tokens back my wallet in main network.

Problem: Not enough ETH for GasFee

**Comment by fluse** [comment]
someone knows to fix it?

**Comment by leonprou** [comment]
Hey @fluse,
Sorry for the late reply
You need Fuse (native on Fuse network) to do so, please contact the support team on Telegram.
