### ISSUE TITLE
Feature Request: API  call for single token balance

### ISSUE THREAD

**Issue by CrackerHax** [fuseio/fuse-studio#92]
add an argument to 'Fetch tokens by owner'

    token (String) tokenAddress

Would like it to return the balance of that particular token held in specified wallet address

**Comment by LiorRabin** [comment]
You can use the explorer API for this:
```
https://explorer.fuse.io/api?module=account&action=tokenbalance&contractaddress={contractAddressHash}&address={addressHash}
```
